[package]
name = "fsevent-sys"
version = "3.0.2"
authors = ["Pierre Baillet <pierre@baillet.name>"]
description = "Rust bindings to the fsevent macOS API for file changes notifications"
license = "MIT"
repository = "https://github.com/octplane/fsevent-rust/tree/master/fsevent-sys"

[dependencies]
libc = "0.2.68"
